- engine/conditions.go
- engine/engine.go
- go.mod
- go.sum
- provider/builtin/provider.go
- provider/lib/lib.go
- provider/provider.go
- provider_settings.json
- rule-example.json
Signed-off-by: Fabian von Feilitzsch <fabian@fabianism.us>
> Implement builtin provider for file/filecontent/xml queries

- engine/engine.go
- main.go
- parser/rule_parser.go
- provider/builtin/provider.go
- provider/golang/provider.go
- provider/java/provider.go
- provider/provider.go
> gracefully shutdown providers and engine

- README.md
> adding demo and overview to the readme

- engine/conditions.go
- engine/engine.go
- engine/engine_test.go
- go.sum
- parser/rule_parser.go
- provider/builtin/provider.go
- provider/golang/provider.go
- provider/java/provider.go
- provider/lib/lib.go
- provider/provider.go
- rule-example.yaml
Following on to #19 and carrying patches. 
The TODO's outstanding after this:
1. Decide on templating language and/or implementation. Using go templates is probably not the best thing to do.
2. Add the ability for other providers to use pipelines (java/golang etc).
3. Find the correct way for a provider/capability to document its template context.
> Pipelining

- .github/workflows/demo-testing.yml
- demo-output.yaml
- engine/conditions.go
- engine/engine.go
- engine/engine_test.go
- go.mod
- hubapi/violations.go
- main.go
- parser/rule_parser.go
- provider/builtin/provider.go
- provider/golang/provider.go
- provider/java/provider.go
- provider/lib/lib.go
- provider/provider.go
- rule-example.yaml
- testing.Dockerfile
> adding demo testing tests

- Dockerfile
- demo-output.yaml
- engine/conditions.go
- main.go
- parser/rule_parser.go
- parser/rule_parser_test.go
- parser/testdata/invalid-message.yaml
- parser/testdata/invalid-rule-id.yaml
- parser/testdata/invalid-rule-invalid-conditions.yaml
- parser/testdata/invalid-rule-no-conditions.yaml
- parser/testdata/rule-and.yaml
- parser/testdata/rule-chain.yaml
- parser/testdata/rule-not-simple.yaml
- parser/testdata/rule-or.yaml
- parser/testdata/rule-simple-default.yaml
- parser/testdata/test-folder/rule-simple-default.yaml
- rule-example.yaml
* Adding test case for unit testing
* Adding test case for demo integration testing of not
fixes #30 
> Adding not keyword for conditions

- parser/rule_parser.go
- parser/rule_parser_test.go
- parser/testdata/invalid-dup-rule-id.yaml
- parser/testdata/or-and-chain-layer.yaml
- parser/testdata/rule-chain.yaml
* adding rules to increase coverage.
fixes #33
> Adding uniqueness validation for rule id while parsing

- .github/workflows/demo-testing.yml
- Dockerfile
> testing that we catch the error now

- demo-output.yaml
- engine/conditions.go
- engine/engine.go
- engine/engine_test.go
- provider/builtin/provider.go
- provider/golang/provider.go
- provider/java/provider.go
- provider/lib/lib.go
- provider/provider.go
- rule-example.yaml
Signed-off-by: Fabian von Feilitzsch <fabian@fabianism.us>
> Passed -> Matched, for clarity

- provider/builtin/provider.go
- provider/golang/provider.go
- provider/java/provider.go
- provider/lib/lib.go
Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>
> Change template context schema to schemaref to allow sharing refs to remote / file schemas

- demo-output.yaml
- dependency/dependency/dep.go
- dependency/main.go
- dependency/provider/golang/provider.go
- dependency/provider/java/provider.go
- dependency/provider/provider.go
- go.mod
- go.sum
> inital POC w/ Runnable

- Dockerfile
- Makefile
- demo-output.yaml
- demo-rules/local-storage.windup-rewrite.yaml
- engine/conditions.go
- examples/customers-tomcat-legacy/.gitignore
- examples/customers-tomcat-legacy/Dockerfile
- examples/customers-tomcat-legacy/Makefile
- examples/customers-tomcat-legacy/pom.xml
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/OrderManagementAppInitializer.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/config/PersistenceConfig.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/config/WebConfig.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/controller/CustomerController.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/exception/ResourceNotFoundException.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/exception/handler/ExceptionHandlingController.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/model/Customer.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/repository/CustomerRepository.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/service/CustomerService.java
- examples/customers-tomcat-legacy/src/main/resources/import.sql
- examples/customers-tomcat-legacy/src/main/resources/persistence.properties
- provider/builtin/provider.go
- provider/java/filter.go
- provider/java/provider.go
- provider_container_settings.json
- rule-example.yaml
- testing.Dockerfile
- windup-testing.Dockerfile
1. Adding ability to call for mulitple locations
2. Adding new rule demo to prove multiple locations
WAIT for the infra to be published before merging
> Adding a windup re-written rule and demo

- demo-rules/local-storage.windup-rewrite.yaml
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/service/CustomerService.java
- examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/service/ICustomerService.java
- provider/java/filter.go
- provider/java/provider.go
> adding inheritance filter

- demo-rules/local-storage.windup-rewrite.yaml
- provider/java/provider.go
Signed-off-by: Shawn Hurley <shawn@hurley.page>
> adding ability to deal with method return type

- demo-rules/local-storage.windup-rewrite.yaml
- engine/engine.go
- provider/java/filter.go
- provider/java/provider.go
Signed-off-by: Shawn Hurley <shawn@hurley.page>
> Adding ability to get variable declartion location types

- .github/workflows/verifyPR.yml
- VERSIONING.md
* Verify that PR title's conform to our scheme
* Add versioning document linking to Konveyor versioning scheme
> :seedling: Add PR title checks

- demo-output.yaml
- engine/conditions.go
- engine/engine.go
- engine/engine_test.go
- hubapi/violations.go
- main.go
- parser/rule_parser.go
- parser/rule_parser_test.go
- parser/testdata/folder-of-rulesets/ruleset-a/rule-simple-default.yaml
- parser/testdata/folder-of-rulesets/ruleset-a/ruleset.yaml
- parser/testdata/folder-of-rulesets/ruleset-b/rule-simple-default.yaml
- parser/testdata/folder-of-rulesets/ruleset-b/ruleset.yaml
- parser/testdata/no-ruleset/rule-simple-default.yaml
- parser/testdata/or-and-chain-layer.yaml
- parser/testdata/rule-chain.yaml
- parser/testdata/rule-not-simple.yaml
- parser/testdata/rule-or.yaml
- parser/testdata/test-folder/ruleset.yaml
- parser/testdata/valid-tag-rule.yaml
- rule-example.yaml
Adding rules to the parser and testing as well as the output.
> :sparkles: Adding ruleset metadata to input and output

- demo-output.yaml
- engine/conditions.go
- engine/engine.go
- hubapi/violations.go
- parser/rule_parser.go
- parser/rule_parser_test.go
- parser/testdata/rule-simple-default.yaml
- provider/provider.go
- rule-example.yaml
Fixes https://github.com/konveyor/analyzer-lsp/issues/62
> :sparkles: Adding rule/violation fields for better user use

- demo-output.yaml
- engine/engine.go
- hubapi/violations.go
> :sparkles: Output tags in violations

- demo-output.yaml
- examples/java/src/main/java/com/example/apps/App.java
- examples/java/src/main/java/com/example/apps/GenericClass.java
- rule-example.yaml
Waiting on https://github.com/konveyor/java-analyzer-bundle/pull/35
fixes #71
> :bug: adding ability to make sure generic classes work

- README.md
- docs/providers.md
> :book: Add provider configuration doc

- engine/engine.go
- engine/engine_test.go
It helps to have the channel processor that is getting results if you are going to buffer the channels.
> :bug: fixing bug, where if more then 10 rules in a set, we would lock

- demo-output.yaml
- parser/rule_parser.go
- provider/java/dependency.go
- provider/java/filter.go
- provider/java/provider.go
- provider/provider.go
- rule-example.yaml
Must wait for https://github.com/konveyor/java-analyzer-bundle/pull/37 to merge.
> :sparkles: Add jar files found to dependencies as well as handle default searches

- provider/provider.go
need to handle multiple matches with regex.
> :bug: Fixing the name-regex-searching

- demo-output.yaml
- docs/providers.md
- docs/rules.md
- engine/conditions.go
- engine/engine.go
- engine/engine_test.go
- hubapi/violations.go
- main.go
- provider/builtin/provider.go
- rule-example.yaml
Adds ability to take tags from a file
Moves tag output to Ruleset level
> :sparkles:  Move tags output from violations to ruleset, take tags from a file

- demo-output.yaml
- dependency/main.go
- dependency/provider/provider.go
- engine/conditions.go
- engine/engine.go
- go.mod
- go.sum
- hubapi/violations.go
- parser/rule_parser.go
- parser/rule_parser_test.go
- provider/builtin/provider.go
- provider/golang/dependency.go
- provider/golang/provider.go
- provider/java/dependency.go
- provider/java/filter.go
- provider/lib/lib.go
- provider/provider.go
- provider/provider_test.go
- rule-example.yaml
> :sparkles: add custom variables and code snippets 

- provider/builtin/provider.go
Discussion needed: I was between this and making builtin.file have a pattern and regex field explicitly. Happy to do it either way.
> :sparkles: Attempt to parse filepatterns as regex, fallback to normal filepath match

- main.go
- tracing/trace.go
Get rid of the annoying messages in log. Fixes #125
> :bug: Disable jaeger by default

- go.mod
- go.sum
- main.go
- parser/rule_parser.go
- provider/builtin/provider.go
* Adding PFlag for CLI flags management.
fixes #127 
fixes #128
> :sparkles: Adding ability to pass multiple rules files or dirs

- README.md
- docs/labels.md
- docs/rules.md
- engine/engine.go
- hubapi/violations.go
Add new labels for source and target tech
Remove old fields from rulesets
Update docs
> :sparkles: : Add new labels for source and target tech, remove tech fields from rulesets

- engine/engine.go
- go.mod
- go.sum
- main.go
> :sparkles: Adding engine configuration pattern and config for limits on incidents

- Dockerfile
- cmd/analyzer/main.go
- parser/rule_parser.go
> :sparkles: Adding the ability to skip dependency rules

- demo-output.yaml
- engine/engine.go
- examples/golang/LICENSE
- rule-example.yaml
> :sparkles: Adding the ability for tags to be templated based on the incidents.

- cmd/dep/main.go
> :bug: changes the output format for dependencies 

- engine/conditions.go
- hubapi/violations.go
Remove source and target technology references in engine.Ruleset and add YAML tags
> :bug: Update engine structs

- docs/labels.md
- docs/rules.md
> :book: Update rule doc

- demo-output.yaml
- rule-example.yaml
> :bug: update demo rule

- Dockerfile
- cmd/dep/main.go
Follow  up with https://github.com/konveyor/analyzer-lsp/issues/212
> :bug: Fix dependency CLI and add it to Dockerfile

- provider/internal/java/filter.go
- provider/internal/java/service_client.go
- provider/internal/java/snipper.go
Making it a constant so that we can use that in the bundle if we wanted to
> :bug: Update filter code to use konveyor-jdt

- cmd/dep/main.go
- hubapi/violations.go
- provider/provider.go
I was moving things around based on a convo with @jortel so that only one package has to be used by external folks.
> :bug: Adding the deps to the external package for the apis

- .github/workflows/demo-testing.yml
> :sparkles: Set our image artifact to delete itself after a day

- .github/workflows/demo-testing.yml
- demo-dep-output.yaml
- demo-output.yaml
- provider/internal/builtin/service_client.go
- provider_container_settings.json
> :bug: add dependency to test, use multiple init configs in demo

- provider/internal/java/dependency.go
- provider/internal/java/provider.go
- provider/internal/java/service_client.go
- provider/internal/java/util.go
> :bug: fix dependencies for binaries

- cmd/analyzer/main.go
- demo-output.yaml
- engine/engine.go
- provider/internal/java/snipper.go
Also disable automatic 80 character line splits from the yaml library.
Closes #200
> :sparkles: Include line number in snip

- engine/labels/labels.go
- engine/labels/labels_test.go
> :bug: allow dots in label values

- engine/labels/labels.go
- engine/labels/labels_test.go
> :bug: allow spaces in label values

- engine/engine.go
- parser/rule_parser.go
> :ghost: Add progress logs 

- demo-output.yaml
- engine/conditions.go
- engine/conditions_test.go
- examples/java/src/main/java/com/example/apps/Singleton.java
- rule-example.yaml
> :sparkles: Chains are now automatically sorted before being executed

- .github/workflows/release-prep.yml
Uses https://github.com/konveyor/release-tools/pull/26
> :sparkles: add workflow to update dockerfile based on release branch creation

- cmd/analyzer/main.go
- provider/provider.go
provider configs should not contain duplicate providers. 
issue: #273
> :bug: Fail right away before initializing any of the providers if we find duplicates in provider config

- provider/internal/builtin/service_client.go
> :bug: Fix empty response in grep

- output/v1/konveyor/violations.go
These tags are needed for static reports
> :ghost: add json tags for output structs

- cmd/analyzer/main.go
- go.mod
- go.sum
Also ran `go mod tidy` which caused the changes in mod and sum
> :bug: restore old option names

- parser/rule_parser.go
> :bug: If all conditions are filtered out, don't add the rule

- cmd/analyzer/main.go
> :bug: analyze command should not run analysis when --help option is set

- parser/rule_parser.go
- provider/provider.go
> :bug: unify conditional interface implementations to either use value or pointer types

- provider/internal/java/provider.go
- provider/internal/java/service_client.go
Allows for the searching of packages. 
Needs  https://github.com/konveyor/java-analyzer-bundle/pull/62
> :sparkles: adding ability to look for packages

- provider/internal/java/dependency.go
> :bug: Don't look for deps in JARs if found in pom.xml

- demo-output.yaml
- provider/internal/java/filter.go
This should correct the off-by-one issues with java line numbers.
> :bug: Add one to line numbers from java bundle

- .gitignore
> :ghost: Ignore Jetbrains config folder (.idea)

- cmd/analyzer/main.go
> :bug: Handle file writing errors as fatal errors

- provider/internal/java/filter.go
- provider/internal/java/service_client.go
- provider/internal/java/snipper.go
- provider/provider.go
- provider/provider_test.go
> :sparkles: only apply dep label selector on dep incidents

- engine/engine.go
> :bug: use the capture groups if they are set

- docs/providers.md
- engine/engine.go
- provider/internal/java/provider.go
- provider/internal/java/service_client.go
> :bug: Set xmx value on JVM to avoid OOMKilled

- provider/internal/java/provider.go
> :bug: Also download deps prior to downloading sources

- provider/internal/java/dependency.go
Fixes #390 
CAUTION: 
* This change only provides a workaround to avoid the SEGV of #390
* It does not find the property contents, the property search should be extended to the parent POM (hierarchy).
> :bug: #390 Workaround to prevent SEGV when POM file has no properties

- provider/internal/java/provider.go
API Tests PR: 55
Fixes https://github.com/konveyor/analyzer-lsp/issues/428
> :bug: Only analyze dependencies if running on source-only mode

- provider/internal/builtin/service_client.go
- rule-example.yaml
Working on increasing the performance inside podman VM's on Mac and Windows.
> :bug: using golang for filecontent searching

- engine/engine.go
> :bug: Keep rule total in output logging

- engine/engine.go
> :bug: Do not create tags for filtered out incidents

- docs/README.md
- docs/incident_selector.md
> :ghost: Adding documentation for incident selector usage

- docs/rules.md
Inside and/or condition blocks.
fixes #463
> :ghost: adding documentation for chaining conditions

- parser/rule_parser.go
> :bug: log yaml parsing errors when parsing rules

- demo-output.yaml
- lsp/base_service_client/base_capabilities.go
> :bug: return code locations in generic provider

- cmd/analyzer/main.go
When getting dependencies during analysis, always retrieve all dependencies
> :bug: Retrieval of dependencies in analysis, is for all deps

- .github/workflows/demo-testing.yml
- Dockerfile
- provider_container_settings.json
fixes https://github.com/konveyor/analyzer-lsp/issues/474
Addon PR: 80
> :bug: Fixing location of provided programs in the base image

- cmd/analyzer/main.go
- cmd/dep/main.go
> :bug: when no dependencies are found do not return an error

- cmd/dep/main.go
> :bug: when no dependencies are found do not return an error (#583)

- .github/workflows/image-build.yaml
- Dockerfile.windows
- external-providers/dotnet-external-provider/Dockerfile.windows
> :seedling: build windows containers for analyzer + .net provider

- external-providers/dotnet-external-provider/pkg/dotnet/provider.go
> :bug: dotnet provider is source only

- .github/workflows/image-build.yaml
Reverts konveyor/analyzer-lsp#630
> Revert ":seedling: standardize windows image tags"

- .github/workflows/image-build.yaml
Reverts konveyor/analyzer-lsp#636
> :ghost: Revert "Revert ":seedling: add tag to image-build environment""

- external-providers/dotnet-external-provider/pkg/dotnet/provider.go
Reverts konveyor/analyzer-lsp#638
> :ghost: Revert "Revert ":bug: dotnet provider is source only""

- demo-output.yaml
- external-providers/java-external-provider/pkg/java_external_provider/provider.go
- external-providers/java-external-provider/pkg/java_external_provider/service_client.go
- rule-example.yaml
Reverts konveyor/analyzer-lsp#639
> :ghost: Revert "Revert ":bug: Be able to process FIELD rules""

- docs/rules.md
Documentation for the news `annotated` feature within the java provider.
- Fixes https://github.com/konveyor/analyzer-lsp/issues/660
> :book: Add annotation matching docs

- demo-output.yaml
- external-providers/java-external-provider/pkg/java_external_provider/provider.go
- external-providers/java-external-provider/pkg/java_external_provider/service_client.go
- provider/provider.go
- rule-example.yaml
See https://github.com/konveyor/analyzer-lsp/issues/718
> :bug: Fix chaining in Java provider (#721)

- external-providers/java-external-provider/pkg/java_external_provider/dependency.go
- external-providers/java-external-provider/pkg/java_external_provider/provider.go
Fixes https://github.com/konveyor/analyzer-lsp/issues/696
> :sparkles: Print maven output on Maven error

- external-providers/java-external-provider/pkg/java_external_provider/dependency.go
- external-providers/java-external-provider/pkg/java_external_provider/provider.go
- external-providers/java-external-provider/pkg/java_external_provider/service_client.go
Fixes https://issues.redhat.com/browse/MTA-4418
> :sparkles: Add insecure maven setting

- docs/rules.md
Some additional information with new location and missing info on description field.
> :book: Add some docs

- engine/engine.go
* Adding context propagation so that rule workers when processing A rule can attach their span to the correct parent
> :bug: handle concurrency issue with updating ruleCTX with scopes

- external-providers/java-external-provider/pkg/java_external_provider/dependency.go
Resolves https://issues.redhat.com/browse/MTA-4636
> :bug: Fix file uri path for deps on windows

- docs/rules.md
> :ghost: Adding notation of a required field for ruleset.yaml file

- engine/conditions.go
- engine/engine.go
- parser/rule_parser.go
> :sparkles: parallelize tagging rules

- external-providers/dotnet-external-provider/Dockerfile
- Remove unnecessary install of go-tools
> :bug: Remove go-tools install in dotnet analyzer

- external-providers/java-external-provider/pkg/java_external_provider/dependency.go
- external-providers/java-external-provider/pkg/java_external_provider/provider.go
- external-providers/java-external-provider/pkg/java_external_provider/service_client.go
Bundle PR: 131
Needs https://github.com/konveyor/java-analyzer-bundle/pull/131
> :bug: MTA-5179 pass in maven local repo path to bundle

- external-providers/java-external-provider/pkg/java_external_provider/util.go
* refactoring the code a little bit.
* adding back the idea of "foundOnline" which we may want to consider renaming.
* adding "is valid" because we really only care if we can create mvn coordinates.
* Adding logs at the base level to make debugging easier.
* Removed a case where we tried to handle if dep was valid but got an error. I don't see how that is possible and I worried that it created confusion.
This will add it to the Cherry-Pick PR to make things easier if/when we merge the main PR.
> :bug: Fixing how we determine deps and what we do with it
