demo-output.yaml
dependency/main.go
dependency/provider/golang/provider.go
dependency/provider/golang/provider_test.go
dependency/provider/java/provider.go
dependency/provider/java/provider_test.go
dependency/provider/provider.go

fixes #59 
- Changes dependency provider interface to return a map of list of dependencies where each key is the direct dependency of the application and indirect dependencies form the list of values for that key. Note that transitive / indirect dependencies are flattened into a list.
- Updates golang / java dep providers to parse dependency in the expected format
In future, the same map can be used to return an adjacency list instead of an absolute list to further maintain the hierarchy within transitive / indirect deps.

Produce hierarchical dependency output

---

engine/conditions.go
engine/engine.go
engine/engine_test.go
parser/rule_parser.go
parser/testdata/or-and-chain-layer.yaml
parser/testdata/rule-chain.yaml
provider/lib/lib.go
provider/provider.go
rule-example.yaml

First steps to making chaining of conditions more intuitive
1. Remove the chain keyword, Or and And do this now.
2. Ordering of from and as does not matter.
TODO: 
Adding a known struct for the output of a condition based on the incidents.
We will continue to have "extras" that will be unstructured.

:sparkles: remove chain keyword order conditions

---

provider/builtin/provider.go

* Look for XML and XHTML files by default
* Attempt to parse XML 1.1 documents as 1.0 until golang supports XML 1.1
* Make error messages for XML parsing more informative

:bug: Increase number of parseable documents for builtin.xml

---

provider/builtin/provider.go

Simple fix to make rule execution continue if a grep condition does not find matches

:bug: Handle grep exit with 1, when it does not find matches

---

Makefile
dependency/main.go

This iterates over all providers in the config and generates dependencies using the ones that provide dep cap

:sparkles: improve CLI for dependency generation

---

demo-output.yaml
hubapi/violations.go
parser/rule_parser.go
parser/rule_parser_test.go
parser/testdata/invalid-category.yaml

Currently choosing to default to potential, as it has the least impact on the end user and captures the uncertainity of the default.
fixes #88

:sparkles: when an invalid category, or no category is set, default it

---

provider/internal/java/provider.go
provider/internal/java/util.go

- Place decompiled java files in a dummy java project maintaining the directory structure for packages
- Walk and decompile all JARs/ WARs within
- Update the dependency path to point to the base of exploded app for us to get .jar names only.

:bug: Decompile files into a java-project for provider to init correctly

---

jsonrpc2/backoff_handler.go
provider/internal/java/provider.go

fixes #147 
Adding back off to failed requests handler for the jsonrpc. This will be usable once we convert to use the correct library.

:bug: adding back off handler and using it for the java

---

engine/engine.go

This allows the substrings to successfully match instead of breaking them completely. Janky solution though, may be better to expand the CodeSnip interface to allow this more easily?

:bug: Strip line numbers from code snips before applying substring matches :bell: 

---

engine/labels/labels.go
external-providers/golang-external-provider/pkg/golang/dependency.go
provider/internal/java/dependency.go
provider/internal/java/dependency_test.go

Pull Request: Refactor Label Manipulation
Description:
Introducing the 'formatLabel' helper function to refactor and centralize key-value label manipulation throughout the codebase. This change addresses the issue of repeated label string manipulation, enhancing code organization and maintainability.
Changes Made:
Added 'formatLabel' function to handle label key-value formatting.
Replaced instances of label construction with calls to 'formatLabel'.
Ensured consistent usage of 'formatLabel' for label manipulation.
Closes #262

:ghost: Refactor Label Manipulation

---

README.md

providers and rules links are not working properly..

:book: fix the Providers and Rules link in README.md file

---

provider/internal/java/dependency.go

Hey in failure scenario I set `d.ResolvedIdentifier` as an empty string (d.ResolvedIdentifier = "").
Let me know if I need to set it to any other value.
I think this is the only function that need to update maybe have to update also `parseMavenDepLines` function .. let me know if I am wrong.
Issue: #175

:bug: Not to fail when dependency SHA cannot be read from file.

---

provider/internal/java/snipper.go

It looks like we are doing unnecessary work multiple times for the same dep in a given run decompiling everytime, we should just do it once

:bug: only decompile for code snips when file isnt present

---

jsonrpc2/backoff_handler.go

This pull request corrects the typo error in backoff_handler.go by replacing ```fmt.Println("deleting request key")``` by ```b.logger.V(7).Info("deleting request key")```

:sparkles:Replacing fmt.Println with logger

---

Dockerfile
cmd/analyzer/main.go
demo.Dockerfile

:sparkles: Added jaeger to images so it runs out of the box

---

engine/engine.go

This pull request addresses issue #295.  I resolved the problem, of duplicate labels appearing both in violations and rules after adding labels from the ruleset, by introducing a function that flags all duplicate values within the labels array.
@pranavgaikwad please check.

:sparkles: Deduplicating Labels

---

external-providers/generic-external-provider/main.go
external-providers/generic-external-provider/pkg/generic/service_client.go
rule-example.yaml

- ~~This is currently failing with Go for... some reason. It can't load packages anymore?~~
- ~~This is probably going to be hideously slow on large projects, the directory tree search will need to be parallelized before this is a feasible approach~~
- I haven't verified that this works with other providers. We should give the experimental python one another try

:sparkles: add fallbacks for when workspace/symbol isn't giving us what we need

---

.github/workflows/demo-testing.yml
cmd/dep/main.go
engine/engine.go
external-providers/generic-external-provider/go.mod
external-providers/generic-external-provider/pkg/generic/dependency.go
external-providers/generic-external-provider/pkg/generic/provider.go
external-providers/generic-external-provider/pkg/generic/service_client.go
parser/rule_parser_test.go
provider/grpc/provider.go
provider/grpc/service_client.go
provider/internal/builtin/provider.go
provider/internal/builtin/service_client.go
provider/internal/java/dependency.go
provider/internal/java/filter.go
provider/internal/java/provider.go
provider/internal/java/service_client.go
provider/internal/java/util.go
provider/provider.go
provider/provider_test.go
provider/server.go

We were using stale context. I observed it when looking at tracer output, some spans were being recorded in the scope of main context, instead of their provider specific context. 
:warning: changes provider api

:warning: always use up-to-date context

---

provider/internal/java/filter.go

Since we moved the decompilation into filter.go, we are now decompiling prior to filtering the incidents out. In that case, for files with .groovy, .kotlin etc, we are decompiling unnecessarily multiple times without knowing that we are anyway going to fail getting incidents from them later on. This was causing some shim tests to take awful lot of time.

:ghost: only decompile when directory doesnt exist

---

engine/labels/labels.go
engine/labels/labels_test.go

Forgot to update the regex which actually does the match, also added a new unit test to catch that flow in future

:bug: Update the label value format  as per new format

---

provider/internal/java/dependency.go
provider/internal/java/provider.go
provider/internal/java/provider_test.go
provider/internal/java/service_client.go
provider/internal/java/util.go
provider/internal/java/util_test.go

Fixes #317 
Fixes #319 
Summary of changes:
* When decompiling binaries, for every JAR we find, we attempt to look at its metadata to get artifact and group. If we dont find metadata, we look it up on maven central using its sha. For all such JARs that we find accurate information about, we add them to java project's pom as dependencies. For all other JARs, we send them to decompile.
* In decompile, we are running concurrently. Also, instead of decompiling each class file individually, we are now decompiling whole JAR using fernflower and then exploding it (this is faster than individual .class file decompile)
* Prior to initing Java provider, we are now downloading sources for all dependencies. If we find any that don't have sources, we are passing them to decompile. 
* When getting …

:sparkles: Identify interesting Jars to decomp and improve decomp performance

---

go.mod
go.sum
provider/internal/java/dependency.go
provider/internal/java/provider.go

Obviously the downside to this is that this command will take considerably longer

:bug: Must compile for dependency:sources to work properly

---

Dockerfile

Added gcc-c++ to the Dockerfile so python-lsp can build. Most likely a stopgap solution until we get better management of lsp servers.

:bug: Fix ppc64le build

---

parser/rule_parser.go
provider/provider.go

:bug: remove dep label selector from dependency condition

---

provider/internal/builtin/service_client.go

The `-E` option in `grep` won't properly handle things like `\n` or `\t`. Using perl regexes fixes the problem.
Current success rate improves marginally, from 68.72% to 68.92%.

:sparkles: Use perl regexes to improve special char handling

---

demo-dep-output.yaml
provider/internal/java/dependency.go
provider/internal/java/provider.go
provider/internal/java/provider_test.go
provider/provider.go

Fixes #384 
- Handle multimodule project dependencies properly
- Only decompile dependencies whose source hasn't been found
Before:
After:
Fixes https://github.com/konveyor/analyzer-lsp/issues/384

:bug: Fix dependency handling

---

provider/internal/java/dependency.go
provider/internal/java/provider.go

Fixes #393 
Remove "compile" goal from maven invocations, as some applications may not be compilable with the JDK version we bundle.
Related to https://github.com/konveyor/analyzer-lsp/issues/393 and https://github.com/konveyor/analyzer-lsp/issues/393

:bug: Fix compile step

---

provider/internal/java/dependency.go
provider/internal/java/provider.go
provider/internal/java/provider_test.go

- Only decompile NOT resolved which don't appear in the RESOLVED list.
- Do not rely on sources classifier
- Maven to output raw (without colors)
- Uses fixed version of the maven-dependency-plugin. This is a temporary fix, until we can get the fix into the plugin and use official versions again.
Depends on https://github.com/konveyor/java-analyzer-bundle/pull/81
Fixes https://github.com/konveyor/analyzer-lsp/issues/406

:bug: Fix source decompilation

---

provider/internal/java/provider.go
provider/internal/java/provider_test.go

API Tests PR: 55
With the new plugin, dependency extraction is simplified to parsing a single line. We also don't need to download dependencies and sources separately; everything is done in a single command. If a dependency is not found in any of the configured repositories, then we won't be able to decompile it (it is absent), therefore we are not interested in those and ignore them.
- Fixes https://github.com/konveyor/analyzer-lsp/issues/423
- We also wouldn't need https://github.com/konveyor/analyzer-lsp/pull/419 anymore

:bug: Use qaware's dependency plugin to avoid all issues related to maven dependency plugin

---

.github/workflows/demo-testing.yml
demo-dep-output.yaml
demo-output.yaml
output/v1/konveyor/violations.go

Fixes #418 
`demo-output.yaml`'s diff looks really ugly, but all this PR does is shuffle some stuff around. 
With this, we may not the `sed` and `yq` stuff in this workflow anymore:
https://github.com/konveyor/analyzer-lsp/blob/740142ea98dbd39b22a63e2da7bfa2374b86be29/.github/workflows/demo-testing.yml#L20-L25

:bug: Implement sorting on structs when marshaling

---

.github/workflows/demo-testing.yml
.gitignore
demo-dep-output.yaml
demo-output.yaml
examples/java/dummy/pom.xml
examples/java/dummy/src/main/java/com/example/apps/Main.java
examples/java/pom.xml
examples/java/src/main/java/com/example/apps/Bean.java

Adding test cases for #390.
The Java example was refactored to make it run (i.e., `mvn compile` at least), and extended by a submodule.
The submodule contains a property based dependency version which cannot be immediately resolved, as there is no `properties` definition in the submodule itself. 
The hotfix provided by #425 prevents the binary from failing. 
Nevertheless, the version property should be resolved from the parent pom which is not yet addressed.
As the bug report only was about the SEGV caused by the problem, #390 may be closed anyway.

:bug: Test cases for #390

---

provider/internal/java/dependency.go

See the playground to prove out we need this:
https://go.dev/play/p/qKDgySCoHwz
fixes MTA-1647 panic on OpenRMS

:bug: fixing panic when the deferenced slice variable is nil

---

cmd/analyzer/main.go
engine/engine.go
engine/internal/variable_labels.go
engine/labels/labels_test.go

First thing to complete the incident filtering on packages from the UI, is to have the CLI option. 
This is the first step toward adding this.

:sparkles: adding incident label selector CLI option

---

provider/internal/builtin/service_client.go
provider/internal/builtin/service_client_test.go
provider/internal/builtin/testdata/pom.xml

We are stripping out empty lines when doing the search, however, in the window that we load into memory we still have to load these empty lines to be able to correctly search content. We only have to get rid of newlines from beginning and the end.

:bug: Use window of correct size in presence of newlines to grab content from xml files

---

Dockerfile

With this change we can at least run as non-root.
I would also proprose moving binaries that need to be accessible to all users be installed in /usr/local/bin. But as of right now it seems we have configs (or something) hard coded to this location.
https://github.com/konveyor/java-analyzer-bundle/blob/main/Dockerfile#L41
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html

:ghost: Improve running as non-root

---

provider/internal/java/dependency.go

Fixes https://github.com/konveyor/analyzer-lsp/issues/482

:bug: Try pom packaging if jar packaging fails

---

demo-output.yaml
examples/java/beans.xml
provider/internal/builtin/service_client.go
rule-example.yaml

:bug: Fix empty code snippet in XML when the match is a key of the node, not an inner value

---

cmd/analyzer/main.go
cmd/dep/main.go

:bug: Write errors to stderr

---

cmd/analyzer/main.go
cmd/dep/main.go

:bug: fixing logs with new command format, adding new format to dep command

---

engine/engine.go
parser/rule_parser.go

:bug: improve logs in parser

---

cmd/analyzer/main.go
provider/internal/java/provider.go
provider/internal/java/util.go

This improves decompilation performance significantly. Also adds more tracing spans so we get more visibility into decomp perf in future.
Before:
* Full analysis via kantra in source + deps mode
_InProgress_
* Decompile performance (41 sec per file, 22451 sec total)
After:
* Full analysis via kantra in source + deps mode (improved by )
```
real	10m21.651s
user	0m1.978s
sys	0m2.554s
```
* Decompile performance (3.1 sec on per file, 1683 sec total, improved by ~93%)
There's one more issue we need to fix. We are decompiling for dependency CLI too. That's because we use the same _Init()_ function for analyzer and dep cli. We either need to combine these two commands, or have an alternate _InitDep()_ function interface on providers that does a light weight init of providers. Captured in …

:bug: improve decompile performance

---

provider/internal/java/service_client.go

There is no need to wait for the build for the init step to be complete.
API tests PR: 102

:sparkles: stop building the project when we don't need anything else

---

.github/workflows/demo-testing.yml
cmd/analyzer/main.go

Make it so that the analysis command can also, in parallel can do the dependency output if desired

:sparkles: adding ability to run dep command during analysis command

---

provider/internal/java/dependency.go
provider/internal/java/util.go
provider/provider.go

:bug: Fix file URI prefix for JARs and do not move found JARs so dependency CLI can still find them

---

provider/provider.go
provider/provider_test.go
provider/testdata/provider_settings_invalid.yaml
provider/testdata/provider_settings_nested_types.json
provider/testdata/provider_settings_simple.yaml

Adding validation of the keys in provider-specific config to only be strings
Adding test cases to validate both JSON and yaml provider settings files will work.
fixes #501

:bug: handle correct structs for protobof init calls

---

demo-output.yaml

This slipped through somehow after merging #351 I should have re-run CI before merging #557

:bug: fix demo output

---

.github/workflows/demo-testing.yml

Reverts konveyor/analyzer-lsp#561

:ghost: Revert ":ghost: workflow must use correct addon branch"

---

cmd/analyzer/main.go
docs/rules.md
provider/internal/builtin/provider.go
provider/internal/builtin/service_client.go
provider/provider.go
rule-example.yaml

* Added new helper to add this to the capability
* used new helper in builtin where we had template context
* I updated the docs to make them clearer.
fixes #527

:sparkles: Adding output/template context to open api spec.

---

.github/workflows/demo-testing.yml
.github/workflows/image-build.yaml
external-providers/generic-external-provider/Dockerfile
external-providers/golang-dependency-provider/Dockerfile
external-providers/java-external-provider/Dockerfile
external-providers/yq-external-provider/Dockerfile

Fixes #470 
I have still kept the original base Dockerfile as-is for backwards compatibility. This is the first step in which we are chaging our demo tests to use the external providers. I will create a follow up issue to track the work around actually making the switch in the addon.

:sparkles: Add dockerfiles for providers and run the demo using the external providers in a Pod

---

provider/internal/builtin/provider.go

Fixes #550 
Added title and description to all the fields mentioned in the issue

:seedling:  Added title and description to capability

---

external-providers/dotnet-external-provider/examples/HelloWorld/README.md

:bug: explain volume mount labeling for podman

---

.github/workflows/image-build.yaml

Bash shell is supported on windows runners.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrunshell

:seedling: force bash shell on windows runner

---

.github/workflows/demo-testing.yml
demo-output.yaml
examples/builtin/inclusion_tests/dir-0/inclusion-test.json
examples/builtin/inclusion_tests/dir-0/inclusion-test.xml
examples/builtin/inclusion_tests/inclusion-test.json
examples/builtin/inclusion_tests/inclusion-test.xml
external-providers/java-external-provider/examples/java/example/src/main/java/com/example/apps/App.java
external-providers/java-external-provider/examples/java/example/src/main/java/com/example/apps/Bean.java
external-providers/java-external-provider/examples/java/example/src/main/java/com/example/apps/util/FileReader.java
external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
provider/internal/builtin/provider.go
provider/internal/builtin/service_client.go
provider/internal/builtin/service_client_test.go
provider/lib.go
provider/provider.go
provider_container_settings.json
provider_local_external_images.json
provider_pod_local_settings.json
rule-example.yaml

:sparkles: Path inclusion

---

demo-output.yaml
engine/engine.go
output/v1/konveyor/violations.go
provider_container_settings.json
provider_local_external_images.json
provider_pod_local_settings.json
rule-example.yaml

*What creates Insights?*
_Rules that do not have an effort value defined or have an effort value of 0, will generate insights._
Depending on what rule actions they define, the output will look different. See following table for all scenarios:
| <rule>.effort | <rule>.tag | <rule>.message |  Description |
| --- | --- | --- | --- |
| 0 | Defined | Not Defined | Rule creates _tags_ and an _insight_. Insight does not contain _message_. |
| 0 | Defined | Defined | Rule creates _tags_ and an _insight_. Insight contains _message_. | 
| 0 | Not Defined | Defined | Rule creates an _insight_. Insight contains _message_. | 
| 1 | Defined | Defined | Rule creates _tags_ and a _violation_. No insights here as effort is non-zero. |
See https://github.com/konveyor/enhancements/edit/master/enhancements/an …

:sparkles: add analysis insights

---

demo-dep-output.yaml
demo-output.yaml
docs/providers.md
external-providers/java-external-provider/pkg/java_external_provider/provider.go
provider_container_settings.json
provider_local_external_images.json
provider_pod_local_settings.json
rule-example.yaml

:sparkles: add ability to pass maven coordinate in location

---

.github/workflows/demo-testing.yml
demo-output.yaml
external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
rule-example.yaml

Enables rule authors to create `java.referenced` conditions with `location: FIELD`.
- Bundle PR: 96
- Fixes https://github.com/konveyor/analyzer-lsp/issues/622

:bug: Be able to process FIELD rules

---

external-providers/dotnet-external-provider/pkg/dotnet/provider.go

Reverts konveyor/analyzer-lsp#629

Revert ":bug: dotnet provider is source only"

---

demo-output.yaml
external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
rule-example.yaml

Reverts konveyor/analyzer-lsp#628

Revert ":bug: Be able to process FIELD rules"

---

.github/workflows/image-build.yaml

Reverts konveyor/analyzer-lsp#637

:ghost:  Revert "Revert ":seedling: standardize windows image tags""

---

external-providers/java-external-provider/pkg/java_external_provider/service_client.go
jsonrpc2/jsonrpc2.go
jsonrpc2/rpcerr.go
jsonrpc2_v2/conn.go
jsonrpc2_v2/rpcerr.go

Solves https://github.com/konveyor/analyzer-lsp/issues/500

:sparkles: Update logging of closed RPC errors

---

external-providers/java-external-provider/pkg/java_external_provider/filter.go

The gradle analysis was uncompressing jars every time because of a lack of a check for the existence of the already decompressed directory.
- Related to https://github.com/konveyor/tackle2-hub/issues/667
- Partly fixes https://github.com/konveyor/analyzer-lsp/issues/662

:bug: Prevent gradle logic from decompressing jars all the time

---

demo-output.yaml
engine/engine.go
external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
rule-example.yaml

This PR adds support for inspecting annotations.
:green_circle: Things that can be done now:
- Check for annotations that are annotating specific `FIELD_DECLARATION`, `METHOD_DECLARATION` or `TYPE`
- Match against `METHOD_DECLARATION`
:red_circle: Things that cannot be done **yet**:
- Match `location: ANNOTATION` and inspect its values.
- Inspect on annotations on `location: CONSTRUCTOR`.
Depends on:
- https://github.com/konveyor/java-analyzer-bundle/pull/104
Fixes:
- https://github.com/konveyor/analyzer-lsp/issues/460
- https://github.com/konveyor/analyzer-lsp/issues/467

:bug: Add annotation inspection support

---

engine/conditions_test.go
engine/engine.go
external-providers/java-external-provider/pkg/java_external_provider/dependency.go
external-providers/java-external-provider/pkg/java_external_provider/dependency_test.go
external-providers/java-external-provider/pkg/java_external_provider/filter.go
external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
external-providers/java-external-provider/pkg/java_external_provider/util.go
external-providers/java-external-provider/pkg/java_external_provider/util_test.go
lsp/protocol/enums.go
lsp/protocol/tsdocument_changes.go
parser/rule_parser.go
parser/rule_parser_test.go
provider/grpc/dependency_resolver_client.go
provider/internal/builtin/provider.go

I assume we used to find the class definition, and then had to find those references, with the updated call I can only assume we are getting the actual usage and the refenece is now finding the places that this is being called.

:bug: use the location from the inital call

---

external-providers/java-external-provider/pkg/java_external_provider/service_client.go

This cuased a problem when the language server is OOM killed and the read step was always waiting causing an indefinite hang. This will timeout these requests.

:bug: adding timeout for RPC call

---

.github/workflows/demo-testing.yml
external-providers/dotnet-external-provider/pkg/dotnet/service_client.go

@djzager 
Basically, when we do our fall back we can find the imports mostly correct, but imports are for namespaces not for actual objects so no definition can be used. Therefore we are getting zero results back for the definiton. 
We can get all the references for the import though, and we can just let the analyzer dedup. 
If you could help get me a windows container image to test with that would helpful (or show me how)

:sparkles: try to get import references when found

---

demo-output.yaml
docs/rules.md
external-providers/java-external-provider/examples/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/controller/CustomerController.java
external-providers/java-external-provider/examples/gradle-multi-project-example/build.gradle
external-providers/java-external-provider/examples/gradle-multi-project-example/gradle/heroku/stage.gradle
rule-example.yaml

:bug: Add rules for annotation inspection queries on location ANNOTATION

---

external-providers/java-external-provider/pkg/java_external_provider/util.go

Java-external-provider: Updated the HTTP GET API call to HTTPS to ensure secure communication with Maven Central Index.
- `external-providers/java-external-provider/pkg/java_external_provider/util.go`: Changed the search URL from `http` to `https` for Maven Central Index API call.

:sparkles: Update Maven Search API HTTP GET request to use HTTPS

---

demo-output.yaml
external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
provider/provider.go
rule-example.yaml

See https://github.com/konveyor/analyzer-lsp/issues/718

:bug: Fix chaining in Java provider

---

.github/workflows/pr-testing.yml
demo-output.yaml
engine/conditions.go
engine/engine.go
engine/scopes.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
external-providers/yq-external-provider/Dockerfile
provider/internal/builtin/service_client.go
provider/lib.go
provider/provider.go

The scope will allow for users to call the engine directly will be able to add information to the condition context. Providers are still responsible for restricting based on that condition context.
Working off of @jmle awesome work to get the file paths respected in providers

:sparkles: Adding a Scope to the running of the rule engine

---

provider/internal/builtin/service_client.go

PR Summary
This pull request introduces a PowerShell-based alternative to the grep command, ensuring that the built-in File Searching feature is also compatible with Windows systems.
service_client.go: Added runOSSpecificGrepCommand to handle grep functionality for both Windows (using PowerShell) and Unix-based systems. This function checks for the OS platform and invokes powershell(windows) and grep(linux). Replaced direct grep command execution with runOSSpecificGrepCommand to support cross-platform compatibility.
service_client.go: Implemented parseGrepOutputForFileContent to parse the output from both PowerShell and grep. This enhancement not only refines the existing parsing mechanism for Linux but also accommodates Windows file path patterns and addresses issues with the split …

:sparkles: Windows Compatibility-Add PowerShell Script as an Alternative to Grep on Linux

---

external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go

This will update and catch the context cancel to close the pipes for stdin and stdout.

:bug: Adding ability for provider and service client to shutdown gracefully

---

external-providers/java-external-provider/pkg/java_external_provider/filter.go

relies on https://github.com/konveyor/java-analyzer-bundle/pull/115

:bug: Remove slash from java bundle for windows

---

provider/grpc/provider.go

Bug fix to address the issue of java-external-provider.exe not ending after analysis completion.
Introduces a cancel context to the NewGRPCClient to ensure proper termination of the gRPC client.
- provider/grpc/provider.go: Added context.WithCancel to manage the lifecycle of the gRPC client and ensure it can be properly stopped.
- provider/grpc/provider.go: Updated grpcProvider struct to include cancelCmd and invoked cancelCmd() in the Stop method to terminate the context.

:bug: Add cancel context to NewGRPCClient

---

docs/rules.md

Improve docs, adding more information about available patterns

:book: Improve docs

---

external-providers/java-external-provider/pkg/java_external_provider/dependency.go
external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go

Fixes https://issues.redhat.com/browse/MTA-4418

:sparkles: CP #755: Add insecure maven setting 

---

engine/engine.go
engine/scopes.go

Adding an additional method on the filter for when a provider doesn't respect the conditioned context completely (think Java search only be at the package, not the file). When using a scope, the user asks for the complete response to be scoped, so the engine should enforce this.

:bug: Handeling the provider not respecting scope by adding Filter in engine

---

engine/conditions.go
engine/scopes.go
provider/provider.go

This only does post discovery filtering. We need to do pre-filtering which is incoming in another PR.

:sparkles: add new scope for excluded patterns [Part 1]

---

demo-output.yaml
external-providers/java-external-provider/pkg/java_external_provider/util.go

:bug: make sure non java files are exploded to java project

---

demo-output.yaml
external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
rule-example.yaml

Adds ability to send CLASS declaration locations to the java provider.
- Issue: https://github.com/konveyor/analyzer-lsp/issues/761#issuecomment-2592922185
Bundle PR: 120

:sparkles: Add CLASS location in java provider

---

external-providers/java-external-provider/pkg/java_external_provider/provider.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
external-providers/java-external-provider/pkg/java_external_provider/util.go

Fixes https://issues.redhat.com/browse/MTA-4484

:sparkles: Allow removing exploded Java bins

---

external-providers/java-external-provider/pkg/java_external_provider/dependency.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go

* When the pom file has changed (by comparing a hash of the file) we will regen the cache.
* this should work for all the cases that have a pom
* there is a TODO to add this behavior for gradle, but that didn't ever seem to be cached.

:sparkles: Adding ability for the cache for dependencies to re-gen

---

engine/conditions.go
engine/engine_test.go

If the incidents were filtered out in the next step, the resulting complete response matched would still be set incorrectly.
We had to filter out not only the engine layer but the ConditionEntry.

:bug: And and Or conditions could pass with exluded data.

---

engine/engine.go

As [this issue](https://github.com/konveyor/kantra/issues/444) in kantra, it's better to show to log processing in the console so user can know how many rules has been processed.
we can specify the log with "process-rule" name so that the kantra CLI can use log hook to select logs print in console.
related PR in kantra: https://github.com/konveyor/kantra/pull/453

:sparkles: add rule progress logs

---

external-providers/java-external-provider/pkg/java_external_provider/service_client.go

This is a stop gap solution to unblock testing, I am currently working on a more thorough approach in jdtls bundle

:bug: increate timeout on wildcard queries

---

engine/labels/labels.go
external-providers/java-external-provider/pkg/java_external_provider/service_client.go
provider/provider.go

Bundle PR: 129
Needs https://github.com/konveyor/java-analyzer-bundle/pull/129
This moves the dep exclusion to the bundle

:sparkles: move open source library exclusion to the bundle
